{% set name = "gridtk" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gridtk-{{ version }}.tar.gz
  sha256: a64154bbb42bc80001299bc25b39faf8b7ff57d60d730fdad6959220b9fa705f

build:
  entry_points:
    - gridtk = gridtk.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - versioningit
    - pip
  run:
    - python >=3.9
    - sqlalchemy >=2.0,<3.dev0
    - tabulate >=0.9.0,<0.10.dev0
    - click >=8.1,<9.dev0

test:
  imports:
    - gridtk
  commands:
    - pip check
    - gridtk --help
  requires:
    - pip

about:
  home: https://pypi.org/project/gridtk/
  summary: 'GridTK: Slurm Job Management for Humans'
  doc_url: https://gridtk.readthedocs.io/
  dev_url: https://github.com/idiap/gridtk
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - anjos
    - 183amir
